name: Linux Build & Tests

on:
  push:
    branches:
      - master
      - dev

jobs:
  build_linux_gcc_clang:
    name: Build Linux | Clang/GCC
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        build_config: [Release, Debug]
        compiler: [clang++-7, clang++-8, clang++-10, g++-8, g++-9, g++-10] #clang++-9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install suitable compiler
        run: sudo apt-get install ${{ matrix.compiler }}

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.15.0'

      - name: Substitute Compiler Name
        uses: bluwy/substitute-string-action@v1
        id: replace_compiler
        with:
          _input-text: ${{ matrix.compiler }}
          clang++: 'clang'
          g++: 'gcc'

      - name: Setup Compiler
        run: |
          echo "CC=${{ steps.replace_compiler.outputs.result }}" >> $GITHUB_ENV
          echo "CXX=${{ matrix.compiler }}" >> $GITHUB_ENV

      - name: Generate Project
        run: cmake -B Build/${{ matrix.build_config }} -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} -G "Ninja"

      - name: Build Kodgen
        run: cmake --build Build/${{ matrix.build_config }} --config ${{ matrix.build_config }} --verbose

      - name: Run Tests
        run: cd Build/${{ matrix.build_config }} && ctest -C ${{ matrix.build_config }} -V