[FileGeneratorSettings]

# Generated files will use this extension
generatedFilesExtension = ".rfk.h"

# List of supported extensions
supportedExtensions		= [".h", ".hpp"]

# Generated files will be located here
outputDirectory			= ""

# Files contained in the directories of this list will be parsed
toParseDirectories		= [
#	"Path/To/Directory/To/Parse"
]

# Files to parse which are not included in any directory of toParseDirectories
toParseFiles			= []

# Files contained in the directories of this list will be ignored
ignoredDirectories		= [
#	"Path/To/Directory/To/Ignore"
]

# Files not to parse which are not included in any directory of ignoredDirectories
ignoredFiles			= []


[FileParserSettings]

# Abort parsing on first encountered error
shouldAbortParsingOnFirstError = true

# Include directories of the project
projectIncludeDirectories	= [
#	Path/To/RefurekuLibrary/Include,
#	Path/To/Your/Project/Include
]

[FileParserSettings.Properties]

propertySeparator = ","
subPropertySeparator = ","
subPropertyStartEncloser = "["
subPropertyEndEncloser = "]"
ignoredCharacters = [ " " ]

[FileParserSettings.Properties.Class]
macroName = "RFKClass"

[FileParserSettings.Properties.Struct]
macroName = "RFKStruct"

[FileParserSettings.Properties.Field]
macroName = "RFKField"

[FileParserSettings.Properties.Method]
macroName = "RFKMethod"

[FileParserSettings.Properties.Enum]
macroName = "RFKEnum"

[FileParserSettings.Properties.EnumValue]
macroName = "RFKEnumVal"