name: Build & Tests

on:
  push:
    branches:
      - master
      - dev
      - CI-setup

jobs:
  build_unix_clang:
    name: Build Unix | Clang
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest
        build_config: [Release, Debug]
        clang_version: [7, 8, 9, 10]

    env:
      CC: clang-${{ matrix.clang_version }}
      CXX: clang++-${{ matrix.clang_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install clang
        run: sudo apt-get install clang-${{ matrix.clang_version }}

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.15.0'

      - name: Check config
        run: |
          ${CC} --version
          ${CXX} --version
          cmake --version

      - name: Build Refureku
        run: |
          cmake -B Build/${{ matrix.build_config }} -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} -DRFK_DEV=1 -DGEN_PROPERTY_RTTI=1 -G "Ninja"
          cmake --build Build/${{ matrix.build_config }} --config ${{ matrix.build_config }} --verbose

      - name: Run tests
        run: cd Build/${{ matrix.build_config }} && ctest -C ${{ matrix.build_config }} -V

  build_unix_gcc:
    name: Build Unix | GCC
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest] # macos-latest
        build_config: [Release, Debug]
        gcc_version: [8, 9, 10]

    env:
      CC: gcc-${{ matrix.gcc_version }}
      CXX: g++-${{ matrix.gcc_version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install GCC
        run: sudo apt-get install g++-${{ matrix.gcc_version }}

      - name: Install ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install CMake
        uses: jwlawson/actions-setup-cmake@v1.8
        with:
          cmake-version: '3.15.0'

      - name: Check config
        run: |
          ${CC} --version
          ${CXX} --version
          cmake --version

      - name: Build Refureku
        run: |
          cmake -B Build/${{ matrix.build_config }} -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} -DRFK_DEV=1 -DGEN_PROPERTY_RTTI=1 -G "Ninja"
          cmake --build Build/${{ matrix.build_config }} --config ${{ matrix.build_config }} --verbose

      - name: Run tests
        run: cd Build/${{ matrix.build_config }} && ctest -C ${{ matrix.build_config }} -V

  build_windows_msvc2019:
    name: Build Windows | MSVC 2019
    runs-on: windows-latest

    strategy:
      matrix:
        msvc_version: [15 2017, 16 2019]
        build_config: [Release, Debug]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Refureku
        run: |
          cmake -B Build/${{ matrix.build_config }} -DCMAKE_BUILD_TYPE=${{ matrix.build_config }} -DRFK_DEV=1 -DGEN_PROPERTY_RTTI=1 -G "Visual Studio ${{ matrix.msvc_version }}" -A x64
          cmake --build Build/${{ matrix.build_config }} --config ${{ matrix.build_config }} --verbose

      - name: Run tests
        run: cd Build/${{ matrix.build_config }} && ctest -C ${{ matrix.build_config }} -V